# Generated by Django 3.0.14 on 2023-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
