# Generated by Django 4.1.5 on 2023-02-10 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicblog',
            name='newuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musicblog',
            name='vote',
            field=models.CharField(blank=True, choices=[('this is so good', 'THIS IS SO GOOD'), ('good but no replay value', 'GOOD BUT NO REPLAY VALUE'), ('i dont like this', 'I DONT LIKE THIS')], max_length=100, null=True),
        ),
    ]
