# Generated by Django 4.2.1 on 2023-05-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(blank=True, choices=[('this is so good', 'THIS IS SO GOOD'), ('good but no replay value', 'GOOD BUT NO REPLAY VALUE'), ('meh, i dont like this', 'MEH, I DONT LIKE THIS')], max_length=100, null=True),
        ),
    ]
