# Generated by Django 4.2.1 on 2023-05-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_vote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(blank=True, choices=[('i\\m adding this to my playlist', "I'M ADDING THIS TO MY PLAYLIST"), ('good but no replay value', 'GOOD BUT NO REPLAY VALUE'), ('meh put it in a trash', 'MEH PUT THIS IN A TRASH')], max_length=100, null=True),
        ),
    ]
