# Generated by Django 4.1.5 on 2023-02-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_musicblog_newuser_musicblog_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(blank=True, choices=[('this is so good', 'THIS IS SO GOOD'), ('good but no replay value', 'GOOD BUT NO REPLAY VALUE'), ('i dont like this', 'I DONT LIKE THIS')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='musicblog',
            name='vote',
        ),
    ]
