# Generated by Django 4.1.7 on 2023-05-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_vote_remove_musicblog_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicblog',
            old_name='newuser',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='musicblog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
